version: '3.3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: gtl_prometheus
        restart: unless-stopped
        volumes:
            - ./monitoring/prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'

    grafana:
        image: grafana/grafana:latest
        container_name: gtl_grafana
        restart: unless-stopped
        links:
            - prometheus:prometheus
        volumes:
            - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
            - grafana_data:/var/lib/grafana
        environment:
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        ports:
            - '3001:3000'
